#ifndef GUARD_CONSTANTS_TMS_HMS_H
#define GUARD_CONSTANTS_TMS_HMS_H

#define FOREACH_TM(F) \
    F(FIRE_FANG) \
    F(DRAGON_CLAW) \
    F(SCALD) \
    F(PSYBLADE) \
    F(PLAY_ROUGH) \
    F(THUNDER_FANG) \
    F(ICE_PUNCH) \
    F(BRICK_BREAK) \
    F(BULLET_SEED) \
    F(FIRE_PUNCH) \
    F(HYPER_VOICE) \
    F(SEED_BOMB) \
    F(ICE_BEAM) \
    F(ENERGY_BALL) \
    F(LIQUIDATION) \
    F(POISON_JAB) \
    F(POWER_GEM) \
    F(SMART_STRIKE) \
    F(GIGA_DRAIN) \
    F(FLASH_CANNON) \
    F(PSYCHIC_FANGS) \
    F(STOMPING_TANTRUM) \
    F(EARTH_POWER) \
    F(THUNDERBOLT) \
    F(SHADOW_CLAW) \
    F(EARTHQUAKE) \
    F(AIR_SLASH) \
    F(DIG) \
    F(PSYCHIC) \
    F(SHADOW_BALL) \
    F(AURA_SPHERE) \
    F(SPIRIT_BREAK) \
    F(DAZZLING_GLEAM) \
    F(THUNDER_PUNCH) \
    F(FLAMETHROWER) \
    F(SLUDGE_BOMB) \
    F(ICE_FANG) \
    F(DRAGON_PULSE) \
    F(ROCK_TOMB) \
    F(DUAL_WINGBEAT) \
    F(NIGHT_SLASH) \
    F(FACADE) \
    F(SECRET_POWER) \
    F(DARK_PULSE) \
    F(METAL_CLAW) \
    F(X_SCISSOR) \
    F(STEEL_WING) \
    F(BUG_BUZZ) \
    F(FALSE_SWIPE) \
    F(OVERHEAT) \
    F(LOW_KICK)

#define FOREACH_HM(F) \
    F(CUT) \
    F(FLY) \
    F(SURF) \
    F(STRENGTH) \
    F(FLASH) \
    F(ROCK_SMASH) \
    F(WATERFALL) \
    F(DIVE)

#define FOREACH_TMHM(F) \
    FOREACH_TM(F) \
    FOREACH_HM(F)

#endif
